DROP TABLE IF EXISTS sjh_emp_tag CASCADE;
DROP TABLE IF EXISTS sjh_emp CASCADE;
DROP TABLE IF EXISTS sjh_dept CASCADE;
DROP TABLE IF EXISTS sjh_sales CASCADE;

CREATE TABLE sjh_dept (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL CONSTRAINT uk_sjh_dept_name UNIQUE,
    budget     NUMERIC(12,2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE sjh_dept IS 'Department';

CREATE TABLE sjh_emp (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_id    INT REFERENCES sjh_dept (id) ON DELETE CASCADE,
    name       VARCHAR(100) NOT NULL,
    email      VARCHAR(200) NOT NULL,
    salary     NUMERIC(10,2),
    active     BOOLEAN DEFAULT TRUE,
    hired      DATE,
    updated_at TIMESTAMP(3),
    photo      BLOB,
    profile    CLOB,
    note       VARCHAR(500) DEFAULT 'n/a',
    uid        UUID
);
COMMENT ON COLUMN sjh_emp.name IS 'Employee name';
CREATE UNIQUE INDEX uk_sjh_emp_email ON sjh_emp (email);
CREATE INDEX idx_sjh_emp_dept_name ON sjh_emp (dept_id, name);

CREATE TABLE sjh_emp_tag (
    emp_id   BIGINT      NOT NULL REFERENCES sjh_emp (id),
    tag_name VARCHAR(50) NOT NULL,
    PRIMARY KEY (emp_id, tag_name)
);

CREATE TABLE sjh_sales (
    id        INT NOT NULL,
    sale_year INT NOT NULL,
    amount    NUMERIC(10,2),
    PRIMARY KEY (id, sale_year)
);

DROP TABLE IF EXISTS sjh_types CASCADE;
DROP SEQUENCE IF EXISTS sjh_order_seq;
CREATE SEQUENCE sjh_order_seq START WITH 1000 INCREMENT BY 10;
CREATE TABLE sjh_types (
    id              INT PRIMARY KEY,
    c_order_no      BIGINT DEFAULT NEXT VALUE FOR sjh_order_seq,
    c_tinyint       TINYINT,
    c_smallint      SMALLINT,
    c_int           INT,
    c_bigint        BIGINT,
    c_numeric       NUMERIC(20,6),
    c_decfloat      DECFLOAT,
    c_real          REAL,
    c_double        DOUBLE PRECISION,
    c_boolean       BOOLEAN,
    c_char          CHAR(10),
    c_varchar       VARCHAR(255),
    c_varchar_ic    VARCHAR_IGNORECASE(255),
    c_clob          CLOB,
    c_binary        BINARY(4),
    c_varbinary     VARBINARY(64),
    c_blob          BLOB,
    c_date          DATE,
    c_time          TIME,
    c_time_tz       TIME WITH TIME ZONE,
    c_timestamp     TIMESTAMP,
    c_timestamp_tz  TIMESTAMP WITH TIME ZONE,
    c_interval      INTERVAL DAY TO SECOND,
    c_uuid          UUID,
    c_json          JSON,
    c_enum          ENUM('red', 'green', 'blue'),
    c_int_array     INTEGER ARRAY,
    c_java_object   JAVA_OBJECT,
    c_gen           BIGINT GENERATED ALWAYS AS (CAST(c_int AS BIGINT) * 2)
);
INSERT INTO sjh_types (id, c_tinyint, c_smallint, c_int, c_bigint, c_numeric, c_decfloat, c_real, c_double, c_boolean,
    c_char, c_varchar, c_varchar_ic, c_clob, c_binary, c_varbinary, c_blob, c_date, c_time, c_time_tz, c_timestamp,
    c_timestamp_tz, c_interval, c_uuid, c_json, c_enum, c_int_array)
VALUES (1, -128, -32768, -2147483648, -9223372036854775808, 12345678901234.123456, 3.14159265358979323846, 3.5,
    2.718281828459045, TRUE, 'char', 'varchar ''quoted'' \ 中文', 'Ignore', 'clob', X'01020304', X'DEADBEEF', X'0102',
    DATE '2024-02-29', TIME '23:59:59', TIME WITH TIME ZONE '12:00:00+08:00', TIMESTAMP '2024-02-29 23:59:59.123456',
    TIMESTAMP WITH TIME ZONE '2024-02-29 12:00:00+08:00', INTERVAL '3 04:05:06' DAY TO SECOND,
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', JSON '{"k":"v","n":[1,2]}', 'red', ARRAY[1, 2, 3]);
INSERT INTO sjh_types (id, c_tinyint, c_smallint, c_int, c_bigint, c_numeric, c_real, c_double, c_boolean, c_char,
    c_varchar, c_date, c_time, c_timestamp)
VALUES (2, 127, 32767, 2147483647, 9223372036854775807, -0.000001, -3.5, -1E100, FALSE, '', '', DATE '1970-01-01',
    TIME '00:00:00', TIMESTAMP '9999-12-31 23:59:59.999999');
INSERT INTO sjh_types (id) VALUES (3);
