CREATE SCHEMA IF NOT EXISTS sjit_src;
DROP TABLE IF EXISTS sjit_src.sjp_emp_tag, sjit_src.sjp_emp, sjit_src.sjp_dept, sjit_src.sjp_sales CASCADE;

CREATE TABLE sjit_src.sjp_dept (
    id         SERIAL PRIMARY KEY,
    name       VARCHAR(100) NOT NULL CONSTRAINT uk_sjp_dept_name UNIQUE,
    budget     NUMERIC(12,2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE sjit_src.sjp_dept IS 'Department';

CREATE TABLE sjit_src.sjp_emp (
    id         BIGSERIAL PRIMARY KEY,
    dept_id    INT REFERENCES sjit_src.sjp_dept (id) ON DELETE CASCADE,
    name       VARCHAR(100) NOT NULL,
    email      VARCHAR(200) NOT NULL,
    salary     NUMERIC(10,2),
    active     BOOLEAN DEFAULT true,
    hired      DATE,
    updated_at TIMESTAMP(3),
    photo      BYTEA,
    profile    TEXT,
    note       VARCHAR(500) DEFAULT 'n/a',
    attrs      JSONB,
    uid        UUID
);
COMMENT ON COLUMN sjit_src.sjp_emp.name IS 'Employee name';
CREATE UNIQUE INDEX uk_sjp_emp_email ON sjit_src.sjp_emp (email);
CREATE INDEX idx_sjp_emp_dept_name ON sjit_src.sjp_emp (dept_id, name);

CREATE TABLE sjit_src.sjp_emp_tag (
    emp_id   BIGINT      NOT NULL REFERENCES sjit_src.sjp_emp (id),
    tag_name VARCHAR(50) NOT NULL,
    PRIMARY KEY (emp_id, tag_name)
);

CREATE TABLE sjit_src.sjp_sales (
    id        INT NOT NULL,
    sale_year INT NOT NULL,
    amount    NUMERIC(10,2),
    PRIMARY KEY (id, sale_year)
) PARTITION BY RANGE (sale_year);
CREATE TABLE sjit_src.sjp_sales_2023 PARTITION OF sjit_src.sjp_sales FOR VALUES FROM (2023) TO (2024);
CREATE TABLE sjit_src.sjp_sales_2024 PARTITION OF sjit_src.sjp_sales FOR VALUES FROM (2024) TO (2025);

DROP TABLE IF EXISTS sjit_src.sjp_types CASCADE;
DROP SEQUENCE IF EXISTS sjit_src.sjp_order_seq;
CREATE SEQUENCE sjit_src.sjp_order_seq START WITH 1000 INCREMENT BY 10;
CREATE TABLE sjit_src.sjp_types (
    id             INT PRIMARY KEY,
    c_order_no     BIGINT DEFAULT nextval('sjit_src.sjp_order_seq'),
    c_smallint     SMALLINT,
    c_integer      INTEGER,
    c_bigint       BIGINT,
    c_numeric      NUMERIC(20,6),
    c_numeric_free NUMERIC,
    c_real         REAL,
    c_double       DOUBLE PRECISION,
    c_money        MONEY,
    c_boolean      BOOLEAN,
    c_char         CHAR(10),
    c_varchar      VARCHAR(255),
    c_varchar_free VARCHAR,
    c_text         TEXT,
    c_bytea        BYTEA,
    c_date         DATE,
    c_time         TIME,
    c_timetz       TIMETZ,
    c_timestamp    TIMESTAMP,
    c_timestamp6   TIMESTAMP(6),
    c_timestamptz  TIMESTAMPTZ,
    c_interval     INTERVAL,
    c_uuid         UUID,
    c_json         JSON,
    c_jsonb        JSONB,
    c_xml          XML,
    c_inet         INET,
    c_cidr         CIDR,
    c_macaddr      MACADDR,
    c_macaddr8     MACADDR8,
    c_bit          BIT(8),
    c_varbit       VARBIT(16),
    c_point        POINT,
    c_line         LINE,
    c_lseg         LSEG,
    c_box          BOX,
    c_path         PATH,
    c_polygon      POLYGON,
    c_circle       CIRCLE,
    c_tsvector     TSVECTOR,
    c_tsquery      TSQUERY,
    c_int4range    INT4RANGE,
    c_int8range    INT8RANGE,
    c_numrange     NUMRANGE,
    c_tsrange      TSRANGE,
    c_tstzrange    TSTZRANGE,
    c_daterange    DATERANGE,
    c_int_array    INT[],
    c_text_array   TEXT[],
    c_oid          OID,
    c_pg_lsn       PG_LSN,
    c_identity     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    c_gen          BIGINT GENERATED ALWAYS AS (c_integer::bigint * 2) STORED
);
INSERT INTO sjit_src.sjp_types (id, c_smallint, c_integer, c_bigint, c_numeric, c_numeric_free, c_real, c_double, c_money,
    c_boolean, c_char, c_varchar, c_varchar_free, c_text, c_bytea, c_date, c_time, c_timetz, c_timestamp, c_timestamp6,
    c_timestamptz, c_interval, c_uuid, c_json, c_jsonb, c_xml, c_inet, c_cidr, c_macaddr, c_macaddr8, c_bit, c_varbit,
    c_point, c_line, c_lseg, c_box, c_path, c_polygon, c_circle, c_tsvector, c_tsquery, c_int4range, c_int8range,
    c_numrange, c_tsrange, c_tstzrange, c_daterange, c_int_array, c_text_array, c_oid, c_pg_lsn)
VALUES (1, -32768, -2147483648, -9223372036854775808, 12345678901234.123456, 3.14159265358979323846264338327950288,
    3.5, 2.718281828459045, 1234.56, true, 'char', 'varchar ''quoted'' \ 中文', 'free', 'text', '\xdeadbeef',
    '2024-02-29', '23:59:59', '12:00:00+08', '2024-02-29 23:59:59', '2024-02-29 23:59:59.123456',
    '2024-02-29 12:00:00+00', '1 year 2 mons 3 days 04:05:06', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    '{"k": "v", "n": [1, 2]}', '{"k": "v"}', '<a>1</a>', '192.168.0.1', '10.0.0.0/8', '08:00:2b:01:02:03',
    '08:00:2b:01:02:03:04:05', B'10101010', B'101', '(1,2)', '{1,-1,0}', '[(0,0),(1,1)]', '((0,0),(1,1))',
    '[(0,0),(1,1),(2,0)]', '((0,0),(1,1),(1,0))', '<(0,0),1>', 'a fat cat', 'fat & cat', '[1,10)', '[1,100)',
    '[1.5,2.5]', '[2024-01-01,2024-12-31)', '[2024-01-01 00:00:00+00,2024-12-31 00:00:00+00)', '[2024-01-01,2024-12-31)',
    '{1,2,3}', '{"a","b c"}', 12345, '16/B374D848');
INSERT INTO sjit_src.sjp_types (id, c_smallint, c_integer, c_bigint, c_numeric, c_numeric_free, c_real, c_double, c_money,
    c_boolean, c_char, c_varchar, c_varchar_free, c_text, c_bytea, c_date, c_time, c_timestamp, c_timestamp6)
VALUES (2, 32767, 2147483647, 9223372036854775807, -0.000001, 0, -3.5, -1E100, -0.01, false, '', '', '', '', '\x',
    '1970-01-01', '00:00:00', '1970-01-01 00:00:00', '9999-12-31 23:59:59.999999');
INSERT INTO sjit_src.sjp_types (id) VALUES (3);
