/*
 * Copyright 2023-2026 Fred Feng
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.sqljam.impexp;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import org.apache.commons.lang3.StringUtils;
import com.github.sqljam.utils.MapUtils;

/**
 * @Description: Dialect generates sql of a database type: type mapping, identifiers, ddl, dml, literals, pagination and value conversion across databases. Differences of old versions are implemented by subclasses
 * @Author: Fred Feng
 * @Date: 24/03/2023
 * @Version 1.0.0
 */
public abstract class Dialect {

    private static final Pattern SIMPLE_IDENTIFIER = Pattern.compile("[A-Za-z_][A-Za-z0-9_$#]*");
    private static final Pattern NUMBER_LITERAL = Pattern.compile("[-+]?\\d+(\\.\\d+)?([eE][-+]?\\d+)?");
    private static final Pattern STRING_LITERAL = Pattern.compile("[nN]?'((?:[^']|'')*)'");
    private static final Pattern PG_CAST = Pattern.compile("^(.*?)::[A-Za-z_][A-Za-z0-9_ .\"]*(\\(\\d+(,\\s*\\d+)?\\))?(\\[\\])?$",
            Pattern.DOTALL);
    private static final Pattern CURRENT_TIMESTAMP = Pattern.compile(
            "(?i)(current_timestamp|now|localtimestamp|getdate|getutcdate|sysdatetime|sysutcdatetime|sysdate|systimestamp|"
                    + "transaction_timestamp|statement_timestamp|clock_timestamp|utc_timestamp|current_datetime)"
                    + "\\s*(\\(\\s*\\d*\\s*\\))?");
    private static final Pattern CURRENT_DATE = Pattern.compile("(?i)(current_date|curdate)\\s*(\\(\\s*\\))?");
    private static final DateTimeFormatter TIMESTAMP_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private static final DateTimeFormatter TIME_FORMATTER = DateTimeFormatter.ofPattern("HH:mm:ss");

    private final TypeNames typeNames = new TypeNames();
    private final Set<String> reservedWords = new HashSet<>();
    /**
     * Column type names generated by this dialect, used to adjust index/constraint statements
     */
    private final Map<String, Map<String, String>> columnTypeNames = new HashMap<>();

    /**
     * Database type which the metadata comes from. <code>null</code> means the same database as this dialect.
     */
    private DbType sourceDbType;
    private IdentifierCase identifierCase = IdentifierCase.AUTO;
    /**
     * When set, table names in DDL/DML generated by this dialect are qualified with these names
     */
    private String targetCatalogName;
    private String targetSchemaName;
    /**
     * Table names are qualified with their source schema names when target schema is not specified
     */
    private boolean sourceSchemaPreserved;
    /**
     * Version of the database which this dialect generates sql for, negative means unknown (latest)
     */
    private int databaseMajorVersion = -1;
    private int databaseMinorVersion = -1;

    protected Dialect() {

        // SQL-92
        registerColumnType(Types.BIT, "bit");
        registerColumnType(Types.BOOLEAN, "boolean");
        registerColumnType(Types.TINYINT, "tinyint");
        registerColumnType(Types.SMALLINT, "smallint");
        registerColumnType(Types.INTEGER, "integer");
        registerColumnType(Types.BIGINT, "bigint");
        registerColumnType(Types.FLOAT, "float($p)");
        registerColumnType(Types.DOUBLE, "double precision");
        registerColumnType(Types.NUMERIC, "numeric($p,$s)");
        registerColumnType(Types.DECIMAL, "decimal($p,$s)");
        registerColumnType(Types.REAL, "real");

        registerColumnType(Types.DATE, "date");
        registerColumnType(Types.TIME, "time");
        registerColumnType(Types.TIMESTAMP, "timestamp");
        registerColumnType(Types.TIME_WITH_TIMEZONE, "time with time zone");
        registerColumnType(Types.TIMESTAMP_WITH_TIMEZONE, "timestamp with time zone");

        registerColumnType(Types.BINARY, "binary($l)");
        registerColumnType(Types.VARBINARY, "bit varying($l)");
        registerColumnType(Types.LONGVARBINARY, "bit varying($l)");
        registerColumnType(Types.BLOB, "blob");

        registerColumnType(Types.CHAR, "char($l)");
        registerColumnType(Types.VARCHAR, "varchar($l)");
        registerColumnType(Types.LONGVARCHAR, "varchar($l)");
        registerColumnType(Types.CLOB, "clob");

        registerColumnType(Types.NCHAR, "nchar($l)");
        registerColumnType(Types.NVARCHAR, "nvarchar($l)");
        registerColumnType(Types.LONGNVARCHAR, "nvarchar($l)");
        registerColumnType(Types.NCLOB, "nclob");
        registerColumnType(Types.SQLXML, "xml");

        registerReservedWords("add", "all", "alter", "and", "any", "as", "asc", "between", "by", "case", "check", "column",
                "comment", "constraint", "create", "cross", "current", "current_date", "current_time",
                "current_timestamp", "current_user", "date", "default", "delete", "desc", "distinct", "drop", "else",
                "end", "except", "exists", "false", "fetch", "for", "foreign", "from", "full", "grant", "group", "having",
                "in", "index", "inner", "insert", "intersect", "into", "is", "join", "key", "left", "level", "like",
                "limit", "natural", "not", "null", "number", "of", "offset", "on", "or", "order", "outer", "primary",
                "references", "right", "row", "rows", "select", "session", "set", "size", "some", "table", "then",
                "to", "true", "union", "unique", "update", "user", "using", "values", "view", "when", "where",
                "with");
    }

    protected void registerColumnType(int code, long capacity, String name) {
        typeNames.put(code, capacity, name);
    }

    protected void registerColumnType(int code, String name) {
        typeNames.put(code, name);
    }

    protected void registerReservedWords(String... words) {
        for (String word : words) {
            reservedWords.add(word.toLowerCase(Locale.ENGLISH));
        }
    }

    public String getTypeName(int code) {
        final String result = typeNames.get(code);
        if (result == null) {
            throw new TypeMappingException("No default type mapping for (java.sql.Types) " + code);
        }
        return result;
    }

    public String getTypeName(int code, long length, int precision, int scale) {
        final String result = typeNames.get(code, length, precision, scale);
        if (result == null) {
            throw new TypeMappingException(
                    String.format("No type mapping for java.sql.Types code: %s, length: %s", code, length));
        }
        return result;
    }

    /**
     * The database type this dialect generates sql for
     */
    public abstract DbType getDbType();

    // ------------------------------------------------------------------
    // Cross database settings
    // ------------------------------------------------------------------

    public DbType getSourceDbType() {
        return sourceDbType;
    }

    public void setSourceDbType(DbType sourceDbType) {
        this.sourceDbType = sourceDbType;
    }

    public boolean isCrossDatabase() {
        return sourceDbType != null && sourceDbType != getDbType();
    }

    public IdentifierCase getIdentifierCase() {
        return identifierCase;
    }

    public void setIdentifierCase(IdentifierCase identifierCase) {
        this.identifierCase = identifierCase != null ? identifierCase : IdentifierCase.AUTO;
    }

    public String getTargetCatalogName() {
        return targetCatalogName;
    }

    public void setTargetCatalogName(String targetCatalogName) {
        this.targetCatalogName = targetCatalogName;
    }

    public String getTargetSchemaName() {
        return targetSchemaName;
    }

    public boolean isSourceSchemaPreserved() {
        return sourceSchemaPreserved;
    }

    public void setSourceSchemaPreserved(boolean sourceSchemaPreserved) {
        this.sourceSchemaPreserved = sourceSchemaPreserved;
    }

    /**
     * Schema name of the table in target database
     */
    public String getTargetSchemaName(String sourceSchemaName) {
        if (StringUtils.isNotBlank(targetSchemaName)) {
            return targetSchemaName;
        }
        return sourceSchemaPreserved && StringUtils.isNotBlank(sourceSchemaName) ? foldIdentifier(sourceSchemaName)
                : null;
    }

    public void setTargetSchemaName(String targetSchemaName) {
        this.targetSchemaName = targetSchemaName;
    }

    public int getDatabaseMajorVersion() {
        return databaseMajorVersion;
    }

    public int getDatabaseMinorVersion() {
        return databaseMinorVersion;
    }

    public void setDatabaseVersion(int majorVersion, int minorVersion) {
        this.databaseMajorVersion = majorVersion;
        this.databaseMinorVersion = minorVersion;
    }

    /**
     * Dialect of the given version of this database type (e.g. Oracle11gDialect), settings of this dialect are copied
     */
    public Dialect forVersion(int majorVersion, int minorVersion) {
        Dialect dialect = getDbType().createDialect(majorVersion, minorVersion);
        dialect.setSourceDbType(sourceDbType);
        dialect.setIdentifierCase(identifierCase);
        dialect.setTargetCatalogName(targetCatalogName);
        dialect.setTargetSchemaName(targetSchemaName);
        dialect.setSourceSchemaPreserved(sourceSchemaPreserved);
        return dialect;
    }

    /**
     * Whether the database version is greater than or equal to the given version. Unknown version is treated as the
     * latest version.
     */
    public boolean isVersionAtLeast(int majorVersion, int minorVersion) {
        if (databaseMajorVersion < 0) {
            return true;
        }
        return databaseMajorVersion > majorVersion
                || (databaseMajorVersion == majorVersion && databaseMinorVersion >= minorVersion);
    }

    // ------------------------------------------------------------------
    // Identifiers
    // ------------------------------------------------------------------

    public String getOpenQuote() {
        return "\"";
    }

    public String getCloseQuote() {
        return "\"";
    }

    /**
     * How the database stores unquoted identifiers. <code>null</code> means case-insensitive.
     */
    public IdentifierCase getStoredIdentifierCase() {
        return null;
    }

    public int getMaxIdentifierLength() {
        return 63;
    }

    public boolean isReservedWord(String word) {
        return word != null && reservedWords.contains(word.toLowerCase(Locale.ENGLISH));
    }

    /**
     * Converts identifier case of a source name to this database's convention
     */
    public String foldIdentifier(String name) {
        if (StringUtils.isBlank(name)) {
            return name;
        }
        switch (identifierCase) {
            case LOWER:
                return name.toLowerCase(Locale.ENGLISH);
            case UPPER:
                return name.toUpperCase(Locale.ENGLISH);
            case KEEP:
                return name;
            default:
                if (!isCrossDatabase()) {
                    return name;
                }
                boolean allLower = name.equals(name.toLowerCase(Locale.ENGLISH));
                boolean allUpper = name.equals(name.toUpperCase(Locale.ENGLISH));
                if (!allLower && !allUpper) {
                    return name;
                }
                return getStoredIdentifierCase() == IdentifierCase.UPPER ? name.toUpperCase(Locale.ENGLISH)
                        : name.toLowerCase(Locale.ENGLISH);
        }
    }

    public boolean isQuoteRequired(String name) {
        if (!SIMPLE_IDENTIFIER.matcher(name).matches() || isReservedWord(name)) {
            return true;
        }
        IdentifierCase stored = getStoredIdentifierCase();
        if (stored == IdentifierCase.UPPER) {
            return !name.equals(name.toUpperCase(Locale.ENGLISH));
        } else if (stored == IdentifierCase.LOWER) {
            return !name.equals(name.toLowerCase(Locale.ENGLISH));
        }
        return false;
    }

    public String quoteIdentifier(String name) {
        if (StringUtils.isBlank(name) || !isQuoteRequired(name)) {
            return name;
        }
        return getOpenQuote() + name.replace(getCloseQuote(), getCloseQuote() + getCloseQuote()) + getCloseQuote();
    }

    /**
     * Folds and quotes an identifier used in generated DDL/DML
     */
    public String getIdentifier(String name) {
        return quoteIdentifier(foldIdentifier(name));
    }

    public String getIdentifiers(String[] names) {
        return Arrays.stream(names).map(this::getIdentifier).collect(Collectors.joining(","));
    }

    /**
     * Comma separated column names (as passed by metadata) to quoted list
     */
    public String getIdentifiers(String names) {
        return getIdentifiers(Arrays.stream(names.split(",")).map(String::trim).toArray(String[]::new));
    }

    /**
     * Table reference used in generated DDL/DML (target side)
     */
    public String getQualifiedTableName(String catalog, String schema, String tableName) {
        String qualifier = getQualifier(targetCatalogName, getTargetSchemaName(schema));
        return StringUtils.isNotBlank(qualifier) ? qualifier + "." + getIdentifier(tableName) : getIdentifier(tableName);
    }

    protected String getQualifier(String catalog, String schema) {
        return StringUtils.isNotBlank(schema) ? getIdentifier(schema) : null;
    }

    /**
     * Fully qualified table reference used for reading from this database (source side)
     */
    public String getSourceTableName(String catalog, String schema, String tableName) {
        StringBuilder ref = new StringBuilder();
        if (StringUtils.isNotBlank(schema)) {
            ref.append(quoteIdentifier(schema)).append(".");
        }
        return ref.append(quoteIdentifier(tableName)).toString();
    }

    /**
     * Truncates the name to the maximum identifier length, keeping it unique with a hash suffix
     */
    public String getLimitedIdentifier(String name) {
        int max = getMaxIdentifierLength();
        if (name == null || name.length() <= max) {
            return name;
        }
        String hash = Integer.toHexString(name.hashCode() & 0x7fffffff);
        return name.substring(0, max - hash.length() - 1) + "_" + hash;
    }

    // ------------------------------------------------------------------
    // DDL
    // ------------------------------------------------------------------

    public abstract String getCreateUserStatement(String username, String password);

    public String[] getStatementAfterUserCreated(String username) {
        return null;
    }

    public abstract String getCreateDatabaseStatement(String catalog, String username);

    public String[] getStatementAfterDatabaseCreated(String catalog, String username) {
        return null;
    }

    /**
     * Creates the schema if it does not exist, returns <code>null</code> if schemas can not be created by sql
     */
    public String getCreateSchemaIfNotExistsStatement(String schema) {
        return null;
    }

    public abstract String getCreateSchemaStatement(String catalog, String schema, String username);

    public String[] getStatementAfterSchemaCreated(String catalog, String schema, String username) {
        return null;
    }

    public String getDefaultSchemaName(String catalog) {
        return null;
    }

    public String getDropTableStatement(String catalog, String schema, String tableName) {
        return String.format("DROP TABLE IF EXISTS %s CASCADE", getQualifiedTableName(catalog, schema, tableName));
    }

    public String getCreateTableStatement(String catalog, String schema, String tableName) {
        return String.format("CREATE TABLE IF NOT EXISTS %s", getQualifiedTableName(catalog, schema, tableName));
    }

    /**
     * Options appended after the closing parenthesis of create table statement, e.g. ENGINE=InnoDB
     */
    public String getTableOptions(String catalog, String schema, String tableName, Map<String, Object> detail) {
        return null;
    }

    /**
     * Creates a sequence, returns <code>null</code> if sequences are not supported
     */
    public String getCreateSequenceStatement(String catalog, String schema, String sequenceName, long startValue,
                                             long increment, Long minValue, Long maxValue, boolean cycle,
                                             Long cacheSize, String dataType) {
        if (!isSequenceSupported()) {
            return null;
        }
        StringBuilder sql = new StringBuilder("CREATE SEQUENCE ");
        sql.append(getQualifiedSequenceName(catalog, schema, sequenceName));
        sql.append(" START WITH ").append(startValue).append(" INCREMENT BY ").append(increment);
        if (minValue != null) {
            sql.append(" MINVALUE ").append(minValue);
        }
        if (maxValue != null && maxValue < Long.MAX_VALUE) {
            sql.append(" MAXVALUE ").append(maxValue);
        }
        if (cycle) {
            sql.append(" CYCLE");
        }
        if (cacheSize != null && cacheSize > 1) {
            sql.append(" CACHE ").append(cacheSize);
        }
        return sql.toString();
    }

    public boolean isSequenceSupported() {
        return false;
    }

    public String[] getStatementBeforeSequenceCreated(String catalog, String schema, String sequenceName) {
        return null;
    }

    /**
     * Statements to make the sequence start with the given value if the sequence already exists
     */
    public String[] getStatementAfterSequenceCreated(String catalog, String schema, String sequenceName,
                                                     long startValue) {
        return null;
    }

    protected String getQualifiedSequenceName(String catalog, String schema, String sequenceName) {
        String qualifier = getQualifier(getTargetCatalogName(), getTargetSchemaName(schema));
        return StringUtils.isNotBlank(qualifier) ? qualifier + "." + getIdentifier(sequenceName)
                : getIdentifier(sequenceName);
    }

    public abstract String getSequenceNameStatement(String catalog, String schema, String tableName, String columnName);

    public abstract String getDefaultSequenceName(String catalog, String schema, String tableName, String columnName);

    public abstract String getAlterSequenceStartValueStatement(String catalog, String schema, String tableName,
                                                               String sequenceName, long startValue);

    /**
     * Statement to reset the identity/auto increment value of a column so that next generated value is startValue
     */
    public String getResetIdentityStatement(String catalog, String schema, String tableName, String columnName,
                                            long startValue) {
        String sequenceName = getDefaultSequenceName(catalog, schema, tableName, columnName);
        return getAlterSequenceStartValueStatement(catalog, schema, tableName, sequenceName, startValue);
    }

    public String[] getStatementAfterTableCreated(String catalog, String schema, String tableName, String username) {
        return null;
    }

    public String getCreatePrimaryKeyStatement(String catalog, String schema, String tableName, String columnName,
                                               String pkeyName) {
        if (StringUtils.isBlank(pkeyName) || pkeyName.startsWith("SYS_") || "PRIMARY".equalsIgnoreCase(pkeyName)
                || pkeyName.startsWith("PK__") || isCrossDatabase()) {
            pkeyName = getLimitedIdentifier(foldIdentifier(tableName) + "_pkey");
            return String.format("CONSTRAINT %s PRIMARY KEY (%s)", quoteIdentifier(pkeyName), getIdentifiers(columnName));
        }
        return String.format("CONSTRAINT %s PRIMARY KEY (%s)", getIdentifier(pkeyName), getIdentifiers(columnName));
    }

    public abstract String getCreateCommentStatement(String catalog, String schema, String tableName, String columnName,
                                                     String comment);

    public String getCreateTableCommentStatement(String catalog, String schema, String tableName, String comment) {
        return String.format("COMMENT ON TABLE %s IS %s", getQualifiedTableName(catalog, schema, tableName), getStringLiteral(comment));
    }

    public String getIndexNameStatement(String catalog, String schema, String tableName, String[] columnNames,
                                        boolean unique,
                                        String indexType) {
        final String indexNamePattern = "%s_%s_%s";
        String name;
        if (unique) {
            name = String.format(indexNamePattern, "uidx", tableName, StringUtils.join(columnNames, "_"));
        } else {
            name = String.format(indexNamePattern, "idx", tableName, StringUtils.join(columnNames, "_"));
        }
        return getLimitedIdentifier(foldIdentifier(name));
    }

    public String getCreateIndexStatement(String catalog, String schema, String tableName, boolean partition,
                                          String[] columnNames,
                                          String indexName, boolean unique, String indexType) {
        if (unique) {
            return String.format("CREATE UNIQUE INDEX IF NOT EXISTS %s ON %s (%s)", quoteIdentifier(indexName),
                    getQualifiedTableName(catalog, schema, tableName), getIdentifiers(columnNames));
        }
        return String.format("CREATE INDEX IF NOT EXISTS %s ON %s (%s)", quoteIdentifier(indexName),
                getQualifiedTableName(catalog, schema, tableName), getIdentifiers(columnNames));
    }

    public String getCreateForeignKeyStatement(String catalog, String schema, String tableName, String fkName,
                                               String[] columnNames, String refTableName, String[] refColumnNames,
                                               String updateRule, String deleteRule) {
        StringBuilder sql = new StringBuilder();
        sql.append(String.format("ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)",
                getQualifiedTableName(catalog, schema, tableName), quoteIdentifier(getLimitedIdentifier(foldIdentifier(fkName))), getIdentifiers(columnNames),
                getQualifiedTableName(catalog, schema, refTableName), getIdentifiers(refColumnNames)));
        if (StringUtils.isNotBlank(deleteRule)) {
            sql.append(" ON DELETE ").append(deleteRule);
        }
        if (StringUtils.isNotBlank(updateRule) && isOnUpdateRuleSupported()) {
            sql.append(" ON UPDATE ").append(updateRule);
        }
        return sql.toString();
    }

    /**
     * Whether foreign keys must be defined in create table statement
     */
    public boolean isForeignKeyInline() {
        return false;
    }

    protected boolean isOnUpdateRuleSupported() {
        return true;
    }

    /**
     * Whether only one identity column is allowed in a table
     */
    public boolean isSingleIncrementalColumn() {
        return false;
    }

    /**
     * Whether identity column must be the primary key
     */
    public boolean isIncrementalColumnKeyRequired() {
        return false;
    }

    /**
     * Statements executed after table created for an identity column, e.g. sequence and trigger of Oracle 11g
     */
    public String[] getStatementAfterIncrementalColumnCreated(String catalog, String schema, String tableName,
                                                              String columnName) {
        return null;
    }

    public abstract String getIncrementalColumnStatement(String catalog, String schema, String tableName, String columnName,
                                                         int dataType,
                                                         String typeName, int columnSize, int columnScale,
                                                         String defaultValue, boolean nullable);

    public String getColumnStatement(String catalog, String schema, String tableName, String columnName, int dataType,
                                     String typeName,
                                     int columnSize, int columnScale, String defaultValue, boolean nullable) {
        StringBuilder columnDef = new StringBuilder(StringHelper.textLeft(getIdentifier(columnName), 30));
        String columnTypeName = getColumnTypeName(dataType, typeName, columnSize, columnScale);
        columnDef.append(StringHelper.textLeft(columnTypeName, 30));
        defaultValue = getDefaultValue(dataType, typeName, defaultValue);
        if (StringUtils.isNotBlank(defaultValue)) {
            columnDef.append(" DEFAULT " + defaultValue);
        }
        if (!nullable) {
            columnDef.append(" NOT NULL");
        }
        return columnDef.toString().trim();
    }

    /**
     * Whether generated (computed) columns are supported by this database version
     */
    public boolean isGeneratedColumnSupported() {
        return true;
    }

    /**
     * Generated (computed/virtual) column of the same database type
     *
     * @param stored whether the value is stored (persisted)
     */
    public String getGeneratedColumnStatement(String catalog, String schema, String tableName, String columnName,
                                              int dataType, String typeName, int columnSize, int columnScale,
                                              String expression, boolean stored) {
        return String.format("%s %s GENERATED ALWAYS AS (%s)%s", getIdentifier(columnName),
                getColumnTypeName(dataType, typeName, columnSize, columnScale), expression, stored ? " STORED" : "");
    }

    /**
     * Column statement with comment, dialects supporting inline comment (MySQL) override it
     */
    public String getColumnStatement(String catalog, String schema, String tableName, String columnName, int dataType,
                                     String typeName, int columnSize, int columnScale, String defaultValue,
                                     boolean nullable, String comment) {
        return getColumnStatement(catalog, schema, tableName, columnName, dataType, typeName, columnSize, columnScale,
                defaultValue, nullable);
    }

    /**
     * Resolves column type of this dialect from jdbc metadata of the source column
     */
    public String getColumnTypeName(int dataType, String typeName, int columnSize, int columnScale) {
        if (isCrossDatabase() && StringUtils.startsWithIgnoreCase(typeName, "interval")) {
            // Interval literals are not compatible across databases
            dataType = Types.VARCHAR;
            columnSize = 100;
            typeName = "varchar";
        }
        if (isCrossDatabase() && getSourceDbType() == DbType.SQLSERVER && dataType == Types.TINYINT) {
            // tinyint of SQL Server is unsigned (0-255)
            dataType = Types.SMALLINT;
        }
        if (isCrossDatabase() && StringUtils.containsIgnoreCase(typeName, "unsigned")) {
            // Unsigned integers of MySQL are widened to keep the value range
            switch (dataType) {
                case Types.TINYINT:
                    dataType = Types.SMALLINT;
                    break;
                case Types.SMALLINT:
                    dataType = Types.INTEGER;
                    break;
                case Types.INTEGER:
                    dataType = Types.BIGINT;
                    break;
                case Types.BIGINT:
                    dataType = Types.NUMERIC;
                    columnSize = 20;
                    columnScale = 0;
                    break;
                default:
                    break;
            }
            if (StringUtils.startsWithIgnoreCase(typeName, "mediumint")) {
                dataType = Types.INTEGER;
            }
            typeName = typeName.replaceAll("(?i)\\s*unsigned", "").replaceAll("(?i)^(tiny|small|medium|big)?int.*",
                    "");
        }
        if (!isCrossDatabase() && StringUtils.isNotBlank(typeName)) {
            String nativeTypeName = getNativeTypeName(dataType, typeName, columnSize, columnScale);
            if (nativeTypeName != null) {
                return nativeTypeName;
            }
        }
        switch (dataType) {
            case -8:
            case -103:
            case -104:
            case -145:
                columnSize = Math.max(columnSize, 64);
                break;
            default:
                break;
        }
        dataType = resolveDataType(dataType, typeName);
        if ("sql_variant".equalsIgnoreCase(typeName)) {
            columnSize = 4000;
        }
        String special = getSpecialTypeName(dataType, StringUtils.defaultString(typeName).toLowerCase(Locale.ENGLISH),
                columnSize, columnScale);
        if (special != null) {
            return special;
        }
        if (dataType == Types.NUMERIC || dataType == Types.DECIMAL) {
            if (columnScale < 0) {
                columnScale = 0;
            }
            if (columnSize <= 0 || columnSize > getMaxNumericPrecision()) {
                return getUnboundedNumericTypeName();
            }
            if (columnScale == 0 && getSourceDbType() == DbType.ORACLE && columnSize <= 19) {
                return columnSize <= 4 ? getTypeName(Types.SMALLINT)
                        : columnSize <= 9 ? getTypeName(Types.INTEGER) : getTypeName(Types.BIGINT);
            }
        }
        if (dataType == Types.ARRAY || dataType == Types.STRUCT || dataType == Types.DISTINCT
                || dataType == Types.REF) {
            dataType = Types.LONGVARCHAR;
            columnSize = Integer.MAX_VALUE;
        }
        try {
            return getTypeName(dataType, columnSize, columnSize, columnScale);
        } catch (TypeMappingException e) {
            // Unknown types are migrated as text
            return getTypeName(Types.LONGVARCHAR, Integer.MAX_VALUE, Integer.MAX_VALUE, 0);
        }
    }

    /**
     * Standard jdbc type of a column by its type code and type name, vendor specific codes are ambiguous
     */
    public static int resolveDataType(int dataType, String typeName) {
        String lowerTypeName = StringUtils.defaultString(typeName).toLowerCase(Locale.ENGLISH);
        switch (lowerTypeName) {
            case "sql_variant":
            case "hierarchyid":
                return lowerTypeName.equals("sql_variant") ? Types.VARCHAR : Types.VARBINARY;
            case "datetime":
            case "smalldatetime":
                return dataType == Types.DATE || dataType == Types.TIMESTAMP ? dataType : Types.TIMESTAMP;
            case "money":
            case "smallmoney":
                return Types.DECIMAL;
            case "geography":
            case "geometry":
                return Types.LONGVARBINARY;
            default:
                return normalizeDataType(dataType);
        }
    }

    /**
     * Converts vendor specific jdbc type codes to standard ones
     */
    public static int normalizeDataType(int dataType) {
        switch (dataType) {
            case -101: // oracle TIMESTAMP WITH TIME ZONE
            case -155: // sql server DATETIMEOFFSET
                return Types.TIMESTAMP_WITH_TIMEZONE;
            case -102: // oracle TIMESTAMP WITH LOCAL TIME ZONE
            case -151: // sql server DATETIME
            case -150: // sql server SMALLDATETIME
                return Types.TIMESTAMP;
            case 100: // oracle BINARY_FLOAT
                return Types.REAL;
            case 101: // oracle BINARY_DOUBLE
                return Types.DOUBLE;
            case -148: // sql server MONEY
            case -146: // sql server SMALLMONEY
                return Types.DECIMAL;
            case -8: // ROWID
            case -103: // oracle INTERVAL YEAR TO MONTH
            case -104: // oracle INTERVAL DAY TO SECOND
            case -145: // sql server GUID
            case -156: // sql server SQL_VARIANT
                return Types.VARCHAR;
            case -157: // sql server GEOMETRY
            case -158: // sql server GEOGRAPHY
                return Types.LONGVARBINARY;
            default:
                return dataType;
        }
    }

    /**
     * Native column type of the same database type, the type name keeps its original case (e.g. enum values)
     */
    protected String getNativeTypeName(int dataType, String sourceTypeName, int columnSize, int columnScale) {
        return null;
    }

    /**
     * Hook for type names which can not be resolved by jdbc type code (json, uuid, ...)
     */
    protected String getSpecialTypeName(int dataType, String sourceTypeName, int columnSize, int columnScale) {
        return null;
    }

    public int getMaxNumericPrecision() {
        return 38;
    }

    public String getUnboundedNumericTypeName() {
        return "numeric";
    }

    public void registerColumnTypeName(String tableName, String columnName, String columnTypeName) {
        MapUtils.getOrCreate(columnTypeNames, tableName, HashMap::new).put(columnName, columnTypeName);
    }

    public String getRegisteredColumnTypeName(String tableName, String columnName) {
        Map<String, String> typeNames = columnTypeNames.get(tableName);
        String typeName = typeNames != null ? typeNames.get(columnName) : null;
        return typeName != null ? typeName.toLowerCase(Locale.ENGLISH) : "";
    }

    // ------------------------------------------------------------------
    // Default values
    // ------------------------------------------------------------------

    public String getCurrentTimestampExpression() {
        return "CURRENT_TIMESTAMP";
    }

    public String getCurrentDateExpression() {
        return "CURRENT_DATE";
    }

    public String getBooleanLiteral(boolean value) {
        return value ? "true" : "false";
    }

    /**
     * Translates the default value expression of the source column to this dialect. Expressions which can not be
     * translated are discarded.
     */
    public String getDefaultValue(int dataType, String typeName, String defaultValue) {
        if (StringUtils.isBlank(defaultValue)) {
            return null;
        }
        defaultValue = defaultValue.trim();
        if (!isCrossDatabase()) {
            return defaultValue;
        }
        String expr = defaultValue.replaceAll("(?is)\\s+on\\s+update\\s+.*$", "");
        boolean changed = true;
        while (changed) {
            changed = false;
            if (expr.startsWith("(") && expr.endsWith(")") && isWrapped(expr)) {
                expr = expr.substring(1, expr.length() - 1).trim();
                changed = true;
            }
            Matcher castMatcher = PG_CAST.matcher(expr);
            if (castMatcher.matches()) {
                expr = castMatcher.group(1).trim();
                changed = true;
            }
        }
        if ("null".equalsIgnoreCase(expr)) {
            return null;
        }
        // BIT(n > 1) of MySQL is a bit string, other BIT columns are booleans
        boolean booleanColumn = dataType == Types.BOOLEAN || "bool".equalsIgnoreCase(typeName)
                || (dataType == Types.BIT && !StringUtils.defaultString(typeName).toLowerCase(Locale.ENGLISH)
                .matches("bit\\((?!1\\))\\d+\\)"));
        if ("true".equalsIgnoreCase(expr) || "b'1'".equalsIgnoreCase(expr)) {
            return getBooleanLiteral(true);
        }
        if ("false".equalsIgnoreCase(expr) || "b'0'".equalsIgnoreCase(expr)) {
            return getBooleanLiteral(false);
        }
        if (NUMBER_LITERAL.matcher(expr).matches()) {
            if (booleanColumn && ("0".equals(expr) || "1".equals(expr))) {
                return getBooleanLiteral("1".equals(expr));
            }
            return expr;
        }
        Matcher stringMatcher = STRING_LITERAL.matcher(expr);
        if (stringMatcher.matches()) {
            String value = stringMatcher.group(1).replace("''", "'");
            if (NUMBER_LITERAL.matcher(value).matches() && isNumericType(dataType)) {
                return value;
            }
            return getStringLiteral(value);
        }
        if (CURRENT_TIMESTAMP.matcher(expr).matches()) {
            return dataType == Types.DATE ? getCurrentDateExpression() : getCurrentTimestampExpression();
        }
        if (CURRENT_DATE.matcher(expr).matches()) {
            return getCurrentDateExpression();
        }
        return null;
    }

    private static boolean isWrapped(String expr) {
        int depth = 0;
        for (int i = 0; i < expr.length(); i++) {
            char c = expr.charAt(i);
            if (c == '(') {
                depth++;
            } else if (c == ')') {
                depth--;
                if (depth == 0 && i != expr.length() - 1) {
                    return false;
                }
            }
        }
        return depth == 0;
    }

    protected static boolean isNumericType(int dataType) {
        switch (dataType) {
            case Types.TINYINT:
            case Types.SMALLINT:
            case Types.INTEGER:
            case Types.BIGINT:
            case Types.FLOAT:
            case Types.REAL:
            case Types.DOUBLE:
            case Types.NUMERIC:
            case Types.DECIMAL:
                return true;
            default:
                return false;
        }
    }

    // ------------------------------------------------------------------
    // Partition
    // ------------------------------------------------------------------

    public String getDefinePartitionTableStatement(String catalog, String schema, String tableName, String partitionType,
                                                   String columnNames) {
        return String.format("PARTITION BY %s (%s)", partitionType, columnNames);
    }

    /**
     * Partition clause with the whole partition detail of the table. Returns <code>null</code> if the partition
     * definition can not be migrated to this dialect.
     */
    public String getDefinePartitionTableStatement(String catalog, String schema, String tableName, String partitionType,
                                                   String columnNames, Map<String, Object> detail) {
        if (isCrossDatabase() || !isPartitionSupported()) {
            return null;
        }
        return getDefinePartitionTableStatement(catalog, schema, tableName, partitionType, columnNames);
    }

    /**
     * Statements which must be executed before creating a partitioned table, e.g. partition function of SQL Server
     */
    public String[] getStatementBeforePartitionTableCreated(String catalog, String schema, String tableName,
                                                      Map<String, Object> detail) {
        return null;
    }

    public boolean isPartitionSupported() {
        return false;
    }

    public abstract String getCreatePartitionTableStatement(String catalog, String schema, String tableName, String inheritedTableName);

    /**
     * Statements executed on each connection before importing, e.g. disabling foreign key checks
     */
    public String[] getSessionStatements() {
        return null;
    }

    public String getScriptCommentPrefix() {
        return "-- ";
    }

    // ------------------------------------------------------------------
    // DML
    // ------------------------------------------------------------------

    public String getInsertTableStatement(String catalog, String schema, String tableName, String[] columnNames) {
        String values = Arrays.stream(columnNames).map(name -> "?").collect(Collectors.joining(","));
        return String.format("INSERT INTO %s(%s) VALUES (%s)", getQualifiedTableName(catalog, schema, tableName), getIdentifiers(columnNames),
                values);
    }

    public String getInsertTableStatement(String catalog, String schema, String tableName, String[] columnNames,
                                          Object[] columnValues) {
        String values = StringUtils.join(columnValues, ",");
        return String.format("INSERT INTO %s(%s) VALUES (%s)", getQualifiedTableName(catalog, schema, tableName), getIdentifiers(columnNames),
                values);
    }

    /**
     * Statements executed before inserting rows with explicit identity values (e.g. SET IDENTITY_INSERT ON)
     */
    public String[] getStatementBeforeInsert(String catalog, String schema, String tableName, boolean identityIncluded) {
        return null;
    }

    public String[] getStatementAfterInsert(String catalog, String schema, String tableName, boolean identityIncluded) {
        return null;
    }

    public String getSelectTableStatement(String catalog, String schema, String tableName) {
        return String.format("SELECT * FROM %s", getSourceTableName(catalog, schema, tableName));
    }

    public String getSelectTableStatement(String catalog, String schema, String tableName, String[] columnNames) {
        return getSelectTableStatement(catalog, schema, tableName, columnNames, null);
    }

    /**
     * Select statement with column expressions by column types
     *
     * @param typeNames type names of columns, may be null
     */
    public String getSelectTableStatement(String catalog, String schema, String tableName, String[] columnNames,
                                          String[] typeNames) {
        List<String> columns = new ArrayList<>();
        for (int i = 0; i < columnNames.length; i++) {
            columns.add(getSelectColumnExpression(columnNames[i], typeNames != null ? typeNames[i] : null));
        }
        return String.format("SELECT %s FROM %s", String.join(",", columns),
                getSourceTableName(catalog, schema, tableName));
    }

    /**
     * Expression of a column in select statement, e.g. converting types which can not be read by jdbc
     */
    public String getSelectColumnExpression(String columnName, String typeName) {
        return quoteIdentifier(columnName);
    }

    public String getCountTableStatement(String catalog, String schema, String tableName) {
        return String.format("SELECT COUNT(*) FROM %s", getSourceTableName(catalog, schema, tableName));
    }

    public String getSelectMaxColumnStatement(String catalog, String schema, String tableName, String columnName) {
        return String.format("SELECT max(%s) FROM %s", quoteIdentifier(columnName), getSourceTableName(catalog, schema, tableName));
    }

    /**
     * Pagination of select statement
     *
     * @param sql     select statement without order by
     * @param orderBy order by columns (comma separated, already quoted), may be null
     */
    public String getPageStatement(String sql, String orderBy, int limit, int offset) {
        StringBuilder page = new StringBuilder(sql);
        if (StringUtils.isNotBlank(orderBy)) {
            page.append(" ORDER BY ").append(orderBy);
        }
        return page.append(String.format(" LIMIT %d OFFSET %d", limit, offset)).toString();
    }

    // ------------------------------------------------------------------
    // Literals
    // ------------------------------------------------------------------

    public String getStringLiteral(String value) {
        if (value == null) {
            return "NULL";
        }
        return "'" + SqlTextUtils.addEscapeChar(value, '\'') + "'";
    }

    /**
     * Placeholder of a LOB value which is restored from LOB file later
     */
    public String getEmptyLobLiteral(boolean binary) {
        return binary ? getBinaryLiteral(new byte[0]) : getStringLiteral("");
    }

    public String getBinaryLiteral(byte[] bytes) {
        return "X'" + toHexString(bytes) + "'";
    }

    public String getTimestampLiteral(LocalDateTime value) {
        return "TIMESTAMP '" + formatTimestamp(value) + "'";
    }

    /**
     * Array literal of the same database type (H2), arrays are migrated as text across databases
     */
    public String getArrayLiteral(String catalog, String schema, String tableName, String columnName,
                                  Object[] values) {
        return Arrays.stream(values).map(value -> getStringValue(catalog, schema, tableName, columnName, value))
                .collect(Collectors.joining(", ", "ARRAY[", "]"));
    }

    public String getTimestampWithTimeZoneLiteral(OffsetDateTime value) {
        return getStringLiteral(formatTimestamp(value.toLocalDateTime()) + value.getOffset());
    }

    public String getDateLiteral(LocalDate value) {
        return "DATE '" + value.format(DATE_FORMATTER) + "'";
    }

    public String getTimeLiteral(LocalTime value) {
        return "TIME '" + formatTime(value) + "'";
    }

    protected static String formatTimestamp(LocalDateTime value) {
        String text = value.format(TIMESTAMP_FORMATTER);
        if (value.getNano() > 0) {
            text += "." + StringUtils.stripEnd(String.format("%09d", value.getNano()), "0");
        }
        return text;
    }

    protected static String formatTime(LocalTime value) {
        String text = value.format(TIME_FORMATTER);
        if (value.getNano() > 0) {
            text += "." + StringUtils.stripEnd(String.format("%09d", value.getNano()), "0");
        }
        return text;
    }

    protected static String toHexString(byte[] bytes) {
        StringBuilder hex = new StringBuilder(bytes.length * 2);
        for (byte b : bytes) {
            hex.append(Character.forDigit((b >> 4) & 0xF, 16)).append(Character.forDigit(b & 0xF, 16));
        }
        return hex.toString().toUpperCase(Locale.ENGLISH);
    }

    public String getStringValue(String catalog, String schema, String tableName, String columnName, Object columnValue) {
        if (columnValue == null) {
            return "NULL";
        }
        if (columnValue instanceof Number) {
            if (columnValue instanceof BigDecimal) {
                return ((BigDecimal) columnValue).toPlainString();
            } else if (columnValue instanceof Double || columnValue instanceof Float) {
                // Scientific notation keeps literals short, e.g. -1.0E100
                double value = ((Number) columnValue).doubleValue();
                if (Double.isNaN(value) || Double.isInfinite(value)) {
                    return "NULL";
                }
                return columnValue.toString();
            }
            return columnValue.toString();
        } else if (columnValue instanceof Character) {
            return getStringLiteral(String.valueOf((Character) columnValue));
        } else if (columnValue instanceof CharSequence) {
            return getStringLiteral(columnValue.toString());
        } else if (columnValue instanceof Boolean) {
            return getBooleanLiteral((Boolean) columnValue);
        } else if (columnValue instanceof byte[]) {
            return getBinaryLiteral((byte[]) columnValue);
        } else if (columnValue instanceof Timestamp) {
            return getTimestampLiteral(((Timestamp) columnValue).toLocalDateTime());
        } else if (columnValue instanceof java.sql.Date) {
            return getDateLiteral(((java.sql.Date) columnValue).toLocalDate());
        } else if (columnValue instanceof java.sql.Time) {
            return getTimeLiteral(((java.sql.Time) columnValue).toLocalTime());
        } else if (columnValue instanceof java.util.Date) {
            return getTimestampLiteral(new Timestamp(((java.util.Date) columnValue).getTime()).toLocalDateTime());
        } else if (columnValue instanceof LocalDateTime) {
            return getTimestampLiteral((LocalDateTime) columnValue);
        } else if (columnValue instanceof LocalDate) {
            return getDateLiteral((LocalDate) columnValue);
        } else if (columnValue instanceof LocalTime) {
            return getTimeLiteral((LocalTime) columnValue);
        } else if (columnValue instanceof OffsetDateTime) {
            return getTimestampWithTimeZoneLiteral((OffsetDateTime) columnValue);
        } else if (columnValue instanceof Object[]) {
            return getArrayLiteral(catalog, schema, tableName, columnName, (Object[]) columnValue);
        } else if (columnValue instanceof java.time.OffsetTime) {
            java.time.OffsetTime time = (java.time.OffsetTime) columnValue;
            return getStringLiteral(formatTime(time.toLocalTime()) + time.getOffset());
        } else if (columnValue instanceof ZonedDateTime) {
            return getTimestampLiteral(((ZonedDateTime) columnValue).toLocalDateTime());
        }
        return getStringLiteral(columnValue.toString());
    }

    /**
     * Converts a value read from source database to a value which can be bound to this database
     */
    public Object getJdbcValue(Object value) {
        return value;
    }

    /**
     * Converts a value of the source column to a value which can be bound to the target column of this database
     *
     * @param sourceDataType jdbc type of source column
     * @param sourceTypeName type name of source column
     * @param columnSize     size of source column
     */
    public Object getJdbcValue(Object value, int sourceDataType, String sourceTypeName, int columnSize) {
        if (value == null) {
            return null;
        }
        if (value instanceof CharSequence && isTemporalType(sourceDataType)) {
            // Dates stored as text (SQLite)
            value = parseTemporal(value.toString(), sourceDataType);
        }
        if (value instanceof Number && (sourceDataType == Types.BOOLEAN
                || (sourceDataType == Types.BIT && columnSize <= 1))) {
            value = ((Number) value).intValue() != 0;
        }
        if (isCrossDatabase()) {
            if (value instanceof CharSequence && "timetz".equalsIgnoreCase(sourceTypeName)) {
                String text = value.toString().replaceAll("([+-]\\d{2})$", "$1:00");
                value = java.time.OffsetTime.parse(text).toLocalTime();
            } else if (sourceDataType == Types.BIT && columnSize > 1) {
                // Bit strings are migrated as integers
                value = toLong(value);
            } else if (value instanceof Object[]) {
                value = Arrays.deepToString((Object[]) value);
            } else if (value instanceof java.time.OffsetTime) {
                value = ((java.time.OffsetTime) value).toLocalTime();
            } else if (value instanceof OffsetDateTime) {
                // Instant in local time zone
                value = ((OffsetDateTime) value).atZoneSameInstant(java.time.ZoneId.systemDefault())
                        .toLocalDateTime();
            }
            // Fractional seconds are truncated, rounding may overflow (e.g. 9999-12-31 23:59:59.9999999)
            if (value instanceof LocalDateTime) {
                value = truncateNanos((LocalDateTime) value);
            } else if (value instanceof LocalTime) {
                value = truncateNanos((LocalTime) value);
            }
        }
        return getJdbcValue(value);
    }

    /**
     * Sql type used to bind NULL of a column
     */
    public int getNullSqlType(int sqlType) {
        return sqlType;
    }

    /**
     * Max digits of fractional seconds supported by this database
     */
    public int getMaxFractionalSecondsPrecision() {
        return 9;
    }

    private LocalDateTime truncateNanos(LocalDateTime value) {
        return value.withNano(truncateNanos(value.getNano()));
    }

    private LocalTime truncateNanos(LocalTime value) {
        return value.withNano(truncateNanos(value.getNano()));
    }

    private int truncateNanos(int nanos) {
        int unit = (int) Math.pow(10, 9 - getMaxFractionalSecondsPrecision());
        return nanos / unit * unit;
    }

    private static boolean isTemporalType(int dataType) {
        return dataType == Types.DATE || dataType == Types.TIME || dataType == Types.TIMESTAMP;
    }

    /**
     * Parses date/time text, returns the text itself if it can not be parsed
     */
    static Object parseTemporal(String text, int dataType) {
        String value = text.trim();
        try {
            if (dataType == Types.TIME) {
                return LocalTime.parse(value);
            }
            if (value.length() == 10) {
                LocalDate date = LocalDate.parse(value);
                return dataType == Types.DATE ? date : date.atStartOfDay();
            }
            LocalDateTime dateTime = LocalDateTime.parse(value.replace(' ', 'T'));
            return dataType == Types.DATE ? dateTime.toLocalDate() : dateTime;
        } catch (RuntimeException e) {
            if (value.matches("-?\\d{10,}")) {
                // Epoch milliseconds
                LocalDateTime dateTime = new Timestamp(Long.parseLong(value)).toLocalDateTime();
                return dataType == Types.DATE ? dateTime.toLocalDate() : dateTime;
            }
            return text;
        }
    }

    private static Object toLong(Object value) {
        if (value instanceof byte[]) {
            long result = 0;
            for (byte b : (byte[]) value) {
                result = (result << 8) | (b & 0xFF);
            }
            return result;
        } else if (value instanceof Boolean) {
            return (Boolean) value ? 1L : 0L;
        } else if (value instanceof Number) {
            return ((Number) value).longValue();
        } else if (value instanceof CharSequence && value.toString().matches("[01]+")) {
            return Long.parseLong(value.toString(), 2);
        }
        return value;
    }

    public Set<String> getReservedWords() {
        return Collections.unmodifiableSet(reservedWords);
    }
}
