/*
 * Copyright 2023-2026 Fred Feng
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.sqljam.impexp;

import org.apache.commons.lang3.StringUtils;
import com.github.sqljam.impexp.ImportExportHandler.ImportConfiguration;

/**
 * @Description: ImportExporter copies tables from a source database into a target database
 * @Author: Fred Feng
 * @Date: 31/03/2023
 * @Version 1.0.0
 */
public class ImportExporter {

    public ImportExporter() {
    }

    private final ImportExportHandler importingExportHandler = new ImportExportHandler();
    private final Exporter exporter = new Exporter(importingExportHandler);
    private IdentifierCase identifierCase;
    private int targetMajorVersion = -1;
    private int targetMinorVersion = -1;

    public Exporter.ExportConfiguration getExportConfiguration() {
        return exporter.getConfiguration();
    }

    public void setMetaDataOperations(MetaDataOperations metaDataOperations) {
        exporter.setMetaDataOperations(metaDataOperations);
    }

    public void setExportListener(ExportListener exportListener) {
        exporter.setExportListener(exportListener);
    }

    public void setIdentifierCase(IdentifierCase identifierCase) {
        this.identifierCase = identifierCase;
    }

    /**
     * Generates ddl/dml for the given version of target database instead of the detected version
     */
    public void setTargetVersion(int majorVersion, int minorVersion) {
        this.targetMajorVersion = majorVersion;
        this.targetMinorVersion = minorVersion;
    }

    public ImportConfiguration getImportConfiguration() {
        return importingExportHandler.getConfiguration();
    }

    /**
     * DDL and DML are generated by the dialect of target database, and table names are qualified with target
     * schema if specified.
     */
    private void prepare() {
        Exporter.ExportConfiguration exportConfiguration = getExportConfiguration();
        ImportConfiguration importConfiguration = getImportConfiguration();
        if (exportConfiguration.getDbType() == null) {
            exportConfiguration.setDbType(DbType.forUrl(exportConfiguration.getUrl()));
        }
        if (importConfiguration.getDbType() == null) {
            importConfiguration.setDbType(DbType.forUrl(importConfiguration.getUrl()));
        }
        Dialect dialect = importConfiguration.getDbType().createDialect();
        dialect.setSourceDbType(exportConfiguration.getDbType());
        if (identifierCase != null) {
            dialect.setIdentifierCase(identifierCase);
        }
        if (StringUtils.isNotBlank(importConfiguration.getTargetSchemaName())) {
            dialect.setTargetCatalogName(importConfiguration.getTargetCatalogName());
            dialect.setTargetSchemaName(importConfiguration.getTargetSchemaName());
        } else if (StringUtils.isNotBlank(importConfiguration.getTargetCatalogName())
                && !importConfiguration.getDbType().isSchemaSupported()) {
            dialect.setTargetCatalogName(importConfiguration.getTargetCatalogName());
        } else if (importConfiguration.getDbType().isSchemaSupported()
                && exportConfiguration.getDbType().isSchemaSupported()) {
            // Schema level import: tables are imported into schemas with the same names
            dialect.setSourceSchemaPreserved(true);
        }
        if (targetMajorVersion >= 0) {
            dialect = dialect.forVersion(targetMajorVersion, Math.max(targetMinorVersion, 0));
        }
        exportConfiguration.setDialect(dialect);
        // Creating user, database and schema is not the business of importing
        exportConfiguration.setShowCreateUserSql(false);
        exportConfiguration.setShowCreateCatalogSql(false);
        exportConfiguration.setShowCreateSchemaSql(false);
    }

    public void export(ExportMode exportMode) throws Exception {
        prepare();
        exporter.export(exportMode);
    }

    public void exportDdlAndData() throws Exception {
        export(ExportMode.DDL_DATA);
    }

    public void exportDdl() throws Exception {
        export(ExportMode.DDL);
    }

    public void exportData() throws Exception {
        export(ExportMode.DATA);
    }
}
