/*
 * Copyright 2023-2026 Fred Feng
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.sqljam.impexp;

import org.apache.commons.lang3.StringUtils;
import com.github.sqljam.impexp.ImportExportHandler.ImportConfiguration;
import com.github.sqljam.jdbc.ConnectionFactory;

/**
 * @Description: ImportExporter copies tables from a source database into a target database
 * @Author: Fred Feng
 * @Date: 31/03/2023
 * @Version 1.0.0
 */
public class ImportExporter {

    public ImportExporter() {
    }

    private final ImportExportHandler importingExportHandler = new ImportExportHandler();
    private final Exporter exporter = new Exporter(importingExportHandler);
    private IdentifierCase identifierCase;
    private Dialect targetDialect;
    private Boolean sourceSchemaPreserved;
    private int targetMajorVersion = -1;
    private int targetMinorVersion = -1;

    public Exporter.ExportConfiguration getExportConfiguration() {
        return exporter.getConfiguration();
    }

    public void setMetaDataOperations(MetaDataOperations metaDataOperations) {
        exporter.setMetaDataOperations(metaDataOperations);
    }

    /**
     * Imports by connections of the factory instead of creating a connection pool, e.g. an existing connection
     * shared by {@link com.github.sqljam.jdbc.SharedConnectionFactory}
     */
    public void setTargetConnectionFactory(ConnectionFactory connectionFactory) {
        importingExportHandler.setConnectionFactory(connectionFactory);
    }

    public void setExportListener(ExportListener exportListener) {
        exporter.setExportListener(exportListener);
    }

    /**
     * Whether tables are imported into schemas with the same names as source schemas when no target schema is
     * given. By default schemas are preserved if both databases support schemas.
     */
    public void setSourceSchemaPreserved(Boolean sourceSchemaPreserved) {
        this.sourceSchemaPreserved = sourceSchemaPreserved;
    }

    /**
     * Dialect of the target database with custom settings, created from the target database type by default
     */
    public void setTargetDialect(Dialect targetDialect) {
        this.targetDialect = targetDialect;
    }

    public void setIdentifierCase(IdentifierCase identifierCase) {
        this.identifierCase = identifierCase;
    }

    /**
     * Generates ddl/dml for the given version of target database instead of the detected version
     */
    public void setTargetVersion(int majorVersion, int minorVersion) {
        this.targetMajorVersion = majorVersion;
        this.targetMinorVersion = minorVersion;
    }

    public ImportConfiguration getImportConfiguration() {
        return importingExportHandler.getConfiguration();
    }

    /**
     * DDL and DML are generated by the dialect of target database, and table names are qualified with target
     * schema if specified.
     */
    private void prepare() {
        Exporter.ExportConfiguration exportConfiguration = getExportConfiguration();
        ImportConfiguration importConfiguration = getImportConfiguration();
        if (exportConfiguration.getDbType() == null) {
            exportConfiguration.setDbType(DbType.forUrl(exportConfiguration.getUrl()));
        }
        if (importConfiguration.getDbType() == null) {
            importConfiguration.setDbType(DbType.forUrl(importConfiguration.getUrl()));
        }
        Dialect dialect = targetDialect != null ? targetDialect : importConfiguration.getDbType().createDialect();
        dialect.setSourceDbType(exportConfiguration.getDbType());
        if (identifierCase != null) {
            dialect.setIdentifierCase(identifierCase);
        }
        dialect.setTableNamePattern(importConfiguration.getTableNamePattern());
        if (!dialect.isTableRenamed() && isSameTables(exportConfiguration, importConfiguration)) {
            // Target tables would be dropped and created before rows are read from them
            throw new ImpExpException("Source and target tables are the same, please choose another schema or a "
                    + "table name pattern such as " + Dialect.TABLE_PLACEHOLDER + "_copy");
        }
        if (StringUtils.isNotBlank(importConfiguration.getTargetSchemaName())) {
            dialect.setTargetCatalogName(importConfiguration.getTargetCatalogName());
            dialect.setTargetSchemaName(importConfiguration.getTargetSchemaName());
        } else if (StringUtils.isNotBlank(importConfiguration.getTargetCatalogName())
                && !importConfiguration.getDbType().isSchemaSupported()) {
            dialect.setTargetCatalogName(importConfiguration.getTargetCatalogName());
        } else if (sourceSchemaPreserved != null) {
            dialect.setSourceSchemaPreserved(sourceSchemaPreserved);
        } else if (importConfiguration.getDbType().isSchemaSupported()
                && exportConfiguration.getDbType().isSchemaSupported()) {
            // Schema level import: tables are imported into schemas with the same names
            dialect.setSourceSchemaPreserved(true);
        }
        if (targetMajorVersion >= 0) {
            dialect = dialect.forVersion(targetMajorVersion, Math.max(targetMinorVersion, 0));
        }
        exportConfiguration.setDialect(dialect);
        // Creating user, database and schema is not the business of importing
        exportConfiguration.setShowCreateUserSql(false);
        exportConfiguration.setShowCreateCatalogSql(false);
        exportConfiguration.setShowCreateSchemaSql(false);
    }

    /**
     * Whether rows would be imported into the tables they are read from: the same database (url) and the same
     * catalog and schema. A target catalog or schema which is not given means the source one.
     */
    static boolean isSameTables(Exporter.ExportConfiguration exportConfiguration,
                                ImportConfiguration importConfiguration) {
        if (exportConfiguration.getDbType() != importConfiguration.getDbType()
                || StringUtils.isBlank(exportConfiguration.getUrl())
                || !StringUtils.equals(exportConfiguration.getUrl().trim(), StringUtils.trim(importConfiguration.getUrl()))) {
            return false;
        }
        return isSameName(exportConfiguration.getIncludedCatalogNames(), importConfiguration.getTargetCatalogName())
                && isSameName(exportConfiguration.getIncludedSchemaNames(), importConfiguration.getTargetSchemaName());
    }

    private static boolean isSameName(String[] sourceNames, String targetName) {
        if (StringUtils.isBlank(targetName) || sourceNames == null || sourceNames.length == 0) {
            return true;
        }
        for (String sourceName : sourceNames) {
            if (targetName.trim().equalsIgnoreCase(StringUtils.trim(sourceName))) {
                return true;
            }
        }
        return false;
    }

    public void export(ExportMode exportMode) throws Exception {
        prepare();
        exporter.export(exportMode);
    }

    public void exportDdlAndData() throws Exception {
        export(ExportMode.DDL_DATA);
    }

    public void exportDdl() throws Exception {
        export(ExportMode.DDL);
    }

    public void exportData() throws Exception {
        export(ExportMode.DATA);
    }
}
