/*
 * Copyright 2023-2026 Fred Feng
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.sqljam.h2;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.charset.StandardCharsets;
import java.sql.Types;

import org.junit.jupiter.api.Test;
import com.github.sqljam.impexp.DbType;
import com.github.sqljam.impexp.db.H2Dialect;

/**
 * @Description: H2DialectTest
 * @Author: Fred Feng
 * @Date: 26/03/2023
 * @Version 1.0.0
 */
class H2DialectTest {

    @Test
    void ddl() {
        H2Dialect dialect = new H2Dialect();
        assertEquals(DbType.H2, dialect.getDbType());
        assertEquals("PUBLIC", dialect.getDefaultSchemaName(null));
        assertEquals("CREATE USER IF NOT EXISTS U PASSWORD 'p'", dialect.getCreateUserStatement("U", "p"));
        assertNull(dialect.getCreateDatabaseStatement("db", "u"));
        assertEquals("CREATE SCHEMA IF NOT EXISTS S", dialect.getCreateSchemaStatement(null, "S", "u"));
        assertEquals("CREATE SCHEMA IF NOT EXISTS S", dialect.getCreateSchemaIfNotExistsStatement("S"));
        assertEquals("ID bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL", dialect.getIncrementalColumnStatement(
                null, null, "T", "ID", Types.NUMERIC, "numeric", 19, 0, null, false).replaceAll("\\s+", " "));
        assertEquals("ALTER TABLE T ALTER COLUMN ID RESTART WITH 10",
                dialect.getResetIdentityStatement(null, null, "T", "ID", 10));
        assertEquals("COMMENT ON COLUMN T.C IS 'x'", dialect.getCreateCommentStatement(null, null, "T", "C", "x"));
        assertTrue(dialect.isSequenceSupported());
        assertEquals("CREATE SEQUENCE IF NOT EXISTS SEQ START WITH 5 INCREMENT BY 1",
                dialect.getCreateSequenceStatement(null, null, "SEQ", 5, 1, null, Long.MAX_VALUE, false, null, null));
        assertEquals("ALTER SEQUENCE SEQ RESTART WITH 5",
                dialect.getStatementAfterSequenceCreated(null, null, "SEQ", 5)[0]);
        assertNull(dialect.getSequenceNameStatement(null, null, "T", "ID"));
        assertNull(dialect.getDefaultSequenceName(null, null, "T", "ID"));
        assertNull(dialect.getAlterSequenceStartValueStatement(null, null, "T", "S", 1));
        assertNull(dialect.getCreatePartitionTableStatement(null, null, "P", "T"));
    }

    @Test
    void types() {
        H2Dialect dialect = new H2Dialect();
        assertEquals("ENUM('red', 'green')", dialect.getColumnTypeName(Types.OTHER, "ENUM('red', 'green')", 5, 0));
        assertEquals("INTEGER ARRAY", dialect.getColumnTypeName(Types.ARRAY, "INTEGER ARRAY", 65536, 0));
        assertEquals("DECFLOAT", dialect.getColumnTypeName(Types.NUMERIC, "DECFLOAT", 100000, 0));
        assertEquals("VARCHAR_IGNORECASE(10)", dialect.getColumnTypeName(Types.VARCHAR, "VARCHAR_IGNORECASE", 10, 0));
        assertEquals("TIMESTAMP(6) WITH TIME ZONE", dialect.getColumnTypeName(Types.TIMESTAMP_WITH_TIMEZONE,
                "TIMESTAMP WITH TIME ZONE", 32, 6));
        assertEquals("CLOB", dialect.getColumnTypeName(Types.CLOB, "CHARACTER LARGE OBJECT", Integer.MAX_VALUE, 0));
        assertEquals("BLOB", dialect.getColumnTypeName(Types.BLOB, "BINARY LARGE OBJECT", Integer.MAX_VALUE, 0));
        assertEquals("varchar(10)", dialect.getColumnTypeName(Types.VARCHAR, "CHARACTER VARYING", 10, 0));

        H2Dialect cross = new H2Dialect();
        cross.setSourceDbType(DbType.MYSQL);
        assertEquals("json", cross.getColumnTypeName(Types.LONGVARCHAR, "json", 0, 0));
        assertEquals("uuid", cross.getColumnTypeName(Types.CHAR, "uniqueidentifier", 36, 0));
        assertEquals("varchar(255)", cross.getColumnTypeName(Types.CHAR, "enum('a','b')", 1, 0));
        assertEquals("clob", cross.getColumnTypeName(Types.LONGVARCHAR, "longtext", 0, 0));
        assertEquals("blob", cross.getColumnTypeName(Types.LONGVARBINARY, "longblob", 0, 0));
        assertEquals("timestamp(6)", cross.getColumnTypeName(Types.TIMESTAMP, "datetime(6)", 26, 6));
        assertEquals("bigint", cross.getColumnTypeName(Types.BIT, "bit(8)", 8, 0));
        assertEquals("smallint", cross.getColumnTypeName(Types.SMALLINT, "year", 4, 0));
    }

    @Test
    void jsonValues() {
        H2Dialect dialect = new H2Dialect();
        assertArrayEquals("{}".getBytes(StandardCharsets.UTF_8), (byte[]) dialect.getJdbcValue("{}", Types.OTHER,
                "JSON", 0));
        assertEquals("x", dialect.getJdbcValue("x", Types.VARCHAR, "varchar", 10));
    }
}
