BEGIN EXECUTE IMMEDIATE 'DROP TABLE sjo_emp_tag CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE sjo_emp CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE sjo_dept CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE sjo_sales CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE sjo_dept (
    id         NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name       VARCHAR2(100) NOT NULL CONSTRAINT uk_sjo_dept_name UNIQUE,
    budget     NUMBER(12,2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);
COMMENT ON TABLE sjo_dept IS 'Department';

CREATE TABLE sjo_emp (
    id         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    dept_id    NUMBER(10) REFERENCES sjo_dept (id) ON DELETE CASCADE,
    name       VARCHAR2(100) NOT NULL,
    email      VARCHAR2(200) NOT NULL,
    salary     NUMBER(10,2),
    active     NUMBER(1) DEFAULT 1,
    hired      DATE,
    updated_at TIMESTAMP(3),
    photo      BLOB,
    profile    CLOB,
    note       VARCHAR2(500) DEFAULT 'n/a'
);
COMMENT ON COLUMN sjo_emp.name IS 'Employee name';
CREATE UNIQUE INDEX uk_sjo_emp_email ON sjo_emp (email);
CREATE INDEX idx_sjo_emp_dept_name ON sjo_emp (dept_id, name);

CREATE TABLE sjo_emp_tag (
    emp_id   NUMBER(19)   NOT NULL REFERENCES sjo_emp (id),
    tag_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY (emp_id, tag_name)
);

CREATE TABLE sjo_sales (
    id        NUMBER(10) NOT NULL,
    sale_year NUMBER(4)  NOT NULL,
    amount    NUMBER(10,2),
    PRIMARY KEY (id, sale_year)
) PARTITION BY RANGE (sale_year) (
    PARTITION p2023 VALUES LESS THAN (2024),
    PARTITION p2024 VALUES LESS THAN (2025),
    PARTITION pmax VALUES LESS THAN (MAXVALUE)
);

BEGIN EXECUTE IMMEDIATE 'DROP TABLE sjo_types CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE sjo_order_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE sjo_order_seq START WITH 1000 INCREMENT BY 10;
CREATE TABLE sjo_types (
    id                NUMBER(10) PRIMARY KEY,
    c_order_no        NUMBER(19) DEFAULT sjo_order_seq.NEXTVAL,
    c_number          NUMBER,
    c_number10        NUMBER(10),
    c_number_ps       NUMBER(20,6),
    c_float           FLOAT,
    c_float10         FLOAT(10),
    c_binary_float    BINARY_FLOAT,
    c_binary_double   BINARY_DOUBLE,
    c_char            CHAR(10),
    c_char_char       CHAR(10 CHAR),
    c_nchar           NCHAR(10),
    c_varchar2        VARCHAR2(255),
    c_varchar2_char   VARCHAR2(255 CHAR),
    c_nvarchar2       NVARCHAR2(255),
    c_clob            CLOB,
    c_nclob           NCLOB,
    c_blob            BLOB,
    c_raw             RAW(16),
    c_long            LONG,
    c_date            DATE,
    c_timestamp       TIMESTAMP,
    c_timestamp3      TIMESTAMP(3),
    c_timestamp_tz    TIMESTAMP WITH TIME ZONE,
    c_timestamp_ltz   TIMESTAMP WITH LOCAL TIME ZONE,
    c_interval_ym     INTERVAL YEAR TO MONTH,
    c_interval_ds     INTERVAL DAY TO SECOND,
    c_rowid           ROWID,
    c_urowid          UROWID,
    c_xml             XMLTYPE,
    c_json            JSON,
    c_boolean         BOOLEAN,
    c_vector          VECTOR(3, FLOAT32),
    c_timestamp9      TIMESTAMP(9),
    c_gen             NUMBER GENERATED ALWAYS AS (c_number10 * 2) VIRTUAL
);
INSERT INTO sjo_types (id, c_number, c_number10, c_number_ps, c_float, c_float10, c_binary_float, c_binary_double,
    c_char, c_char_char, c_nchar, c_varchar2, c_varchar2_char, c_nvarchar2, c_clob, c_nclob, c_blob, c_raw, c_long,
    c_date, c_timestamp, c_timestamp3, c_timestamp_tz, c_timestamp_ltz, c_interval_ym, c_interval_ds, c_rowid,
    c_urowid, c_xml, c_json, c_boolean)
VALUES (1, 3.14159265358979323846264338327950288, -2147483648, 12345678901234.123456, 1.5, 2.5, 3.5, 2.718281828459045,
    'char', 'char', N'中文', 'varchar ''quoted'' \', 'varchar2 中文', N'nvarchar2 中文', 'clob', N'nclob 中文',
    HEXTORAW('DEADBEEF'), HEXTORAW('01020304'), 'long text', DATE '2024-02-29', TIMESTAMP '2024-02-29 23:59:59',
    TIMESTAMP '2024-02-29 23:59:59.123', TIMESTAMP '2024-02-29 12:00:00 +08:00', TIMESTAMP '2024-02-29 12:00:00',
    INTERVAL '1-2' YEAR TO MONTH, INTERVAL '3 04:05:06.789' DAY TO SECOND, 'AAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAA',
    XMLTYPE('<a>1</a>'), '{"k": "v", "n": [1, 2]}', TRUE);
INSERT INTO sjo_types (id, c_number, c_number10, c_number_ps, c_float, c_float10, c_binary_float, c_binary_double,
    c_char, c_varchar2, c_clob, c_blob, c_raw, c_date, c_timestamp, c_boolean)
VALUES (2, 0, 2147483647, -0.000001, -1.5, 0, -3.5, -1E100, ' ', ' ', ' ', EMPTY_BLOB(), HEXTORAW('00'),
    DATE '1970-01-01', TIMESTAMP '9999-12-31 23:59:59.999999', FALSE);
INSERT INTO sjo_types (id) VALUES (3);
UPDATE sjo_types SET c_vector = TO_VECTOR('[1, 2.5, -3]', 3, FLOAT32),
    c_timestamp9 = TIMESTAMP '2024-02-29 12:00:00.123456789' WHERE id = 1;
UPDATE sjo_types SET c_vector = TO_VECTOR('[0, 0, 0]', 3, FLOAT32),
    c_timestamp9 = TIMESTAMP '1970-01-01 00:00:00.000000001' WHERE id = 2;
