/*
 * Copyright 2023-2026 Fred Feng
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.sqljam.oracle;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Types;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.HashMap;
import java.util.Map;

import org.junit.jupiter.api.Test;
import com.github.sqljam.impexp.DbType;
import com.github.sqljam.impexp.db.Oracle11gDialect;
import com.github.sqljam.impexp.db.Oracle12cDialect;
import com.github.sqljam.impexp.db.OracleDialect;

/**
 * @Description: OracleDialectTest
 * @Author: Fred Feng
 * @Date: 26/03/2023
 * @Version 1.0.0
 */
class OracleDialectTest {

    @Test
    void ddl() {
        OracleDialect dialect = new OracleDialect();
        assertEquals(DbType.ORACLE, dialect.getDbType());
        assertEquals("CREATE USER U IDENTIFIED BY \"p\"", dialect.getCreateUserStatement("U", "p"));
        assertEquals("GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO U",
                dialect.getStatementAfterUserCreated("U")[0]);
        assertNull(dialect.getCreateDatabaseStatement("db", "u"));
        assertNull(dialect.getCreateSchemaStatement(null, "s", "u"));
        assertNull(dialect.getCreateSchemaIfNotExistsStatement("s"));
        assertEquals("CREATE TABLE T", dialect.getCreateTableStatement(null, null, "T"));
        assertTrue(dialect.getDropTableStatement(null, null, "T").contains(
                "EXECUTE IMMEDIATE 'DROP TABLE T CASCADE CONSTRAINTS PURGE'"));
        assertEquals("COMMENT ON COLUMN T.C IS 'x'", dialect.getCreateCommentStatement(null, null, "T", "C", "x"));
        assertEquals("CREATE UNIQUE INDEX IDX ON T (A)", dialect.getCreateIndexStatement(null, null, "T", false,
                new String[]{"A"}, "IDX", true, null));
        dialect.registerColumnTypeName("T", "BODY", "CLOB");
        assertNull(dialect.getCreateIndexStatement(null, null, "T", false, new String[]{"BODY"}, "IDX", false, null));
        assertTrue(dialect.getCreateForeignKeyStatement(null, null, "T", "FK", new String[]{"A"}, "R",
                new String[]{"ID"}, "CASCADE", "SET DEFAULT").endsWith("REFERENCES R (ID)"));
        assertEquals("C NUMBER GENERATED ALWAYS AS (A * 2) VIRTUAL", dialect.getGeneratedColumnStatement(null, null,
                "T", "C", Types.NUMERIC, "NUMBER", 0, 0, "A * 2", false));
        assertEquals("SYSTIMESTAMP", dialect.getCurrentTimestampExpression());
        assertEquals("SYSDATE", dialect.getCurrentDateExpression());
        assertEquals("EMPTY_CLOB()", dialect.getEmptyLobLiteral(false));
        assertEquals("EMPTY_BLOB()", dialect.getEmptyLobLiteral(true));
    }

    @Test
    void identityByVersion() {
        OracleDialect dialect = new OracleDialect();
        assertEquals(128, dialect.getMaxIdentifierLength());
        assertEquals("ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL",
                dialect.getIncrementalColumnStatement(null, null, "T", "ID", Types.BIGINT, "bigint", 19, 0, null,
                        false).replaceAll("\\s+", " "));
        assertNull(dialect.getStatementAfterIncrementalColumnCreated(null, null, "T", "ID"));
        assertEquals("ALTER TABLE T MODIFY ID GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 10)",
                dialect.getResetIdentityStatement(null, null, "T", "ID", 10));
        assertEquals("SELECT * FROM T ORDER BY ID OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY",
                dialect.getPageStatement("SELECT * FROM T", "ID", 10, 20));

        assertEquals(30, new Oracle12cDialect().getMaxIdentifierLength());
        // Oracle 11g: sequence and trigger, ROWNUM pagination
        dialect = (OracleDialect) dialect.forVersion(11, 2);
        assertTrue(dialect instanceof Oracle11gDialect);
        assertEquals(30, dialect.getMaxIdentifierLength());
        assertEquals("ID NUMBER(19) NOT NULL", dialect.getIncrementalColumnStatement(null, null, "T", "ID",
                Types.VARCHAR, "varchar", 10, 0, null, false).replaceAll("\\s+", " "));
        String[] statements = dialect.getStatementAfterIncrementalColumnCreated(null, null, "T", "ID");
        assertTrue(statements[0].contains("CREATE SEQUENCE SEQ_T START WITH 1"));
        assertTrue(statements[1].startsWith("CREATE OR REPLACE TRIGGER TRG_T BEFORE INSERT ON T"));
        assertTrue(dialect.getResetIdentityStatement(null, null, "T", "ID", 10).contains(
                "CREATE SEQUENCE SEQ_T START WITH 10"));
        assertEquals("SELECT * FROM (SELECT t__.*, ROWNUM rn__ FROM (SELECT * FROM T ORDER BY ID) t__"
                        + " WHERE ROWNUM <= 30) WHERE rn__ > 20",
                dialect.getPageStatement("SELECT * FROM T", "ID", 10, 20));
        dialect.setTargetSchemaName("FENGY");
        assertTrue(dialect.getStatementAfterIncrementalColumnCreated(null, null, "T", "ID")[0].contains(
                "FENGY.SEQ_T"));
    }

    @Test
    void sequences() {
        OracleDialect dialect = new OracleDialect();
        assertTrue(dialect.isSequenceSupported());
        assertTrue(dialect.getStatementBeforeSequenceCreated(null, null, "SEQ")[0].contains("DROP SEQUENCE SEQ"));
        assertEquals("CREATE SEQUENCE SEQ START WITH 1000 INCREMENT BY 10 NOCACHE",
                dialect.getCreateSequenceStatement(null, null, "SEQ", 1000, 10, null, null, false, 1L, null));
        assertNull(dialect.getAlterSequenceStartValueStatement(null, null, "T", "S", 1));
        assertNull(dialect.getSequenceNameStatement(null, null, "T", "ID"));
        assertNull(dialect.getDefaultSequenceName(null, null, "T", "ID"));
    }

    @Test
    void types() {
        OracleDialect dialect = new OracleDialect();
        assertEquals("NUMBER(10,2)", dialect.getColumnTypeName(Types.NUMERIC, "NUMBER", 10, 2));
        assertEquals("NUMBER(10)", dialect.getColumnTypeName(Types.NUMERIC, "NUMBER", 10, 0));
        assertEquals("NUMBER", dialect.getColumnTypeName(Types.NUMERIC, "NUMBER", 0, -127));
        assertEquals("TIMESTAMP(6) WITH TIME ZONE", dialect.getColumnTypeName(-101, "TIMESTAMP(6) WITH TIME ZONE",
                13, 6));
        assertEquals("VARCHAR2(20)", dialect.getColumnTypeName(Types.VARCHAR, "VARCHAR2", 20, 0));
        assertEquals("FLOAT(126)", dialect.getColumnTypeName(Types.FLOAT, "FLOAT", 126, 0));
        assertEquals("DATE", dialect.getColumnTypeName(Types.TIMESTAMP, "DATE", 7, 0));

        OracleDialect cross = new OracleDialect();
        cross.setSourceDbType(DbType.MYSQL);
        assertEquals("VARCHAR2(255 CHAR)", cross.getColumnTypeName(Types.VARCHAR, "varchar(255)", 255, 0));
        assertEquals("CLOB", cross.getColumnTypeName(Types.VARCHAR, "varchar", 10000, 0));
        assertEquals("CLOB", cross.getColumnTypeName(Types.LONGVARCHAR, "json", 0, 0));
        assertEquals("BLOB", cross.getColumnTypeName(Types.LONGVARBINARY, "longblob", 0, 0));
        assertEquals("VARCHAR2(255 CHAR)", cross.getColumnTypeName(Types.CHAR, "enum('a')", 1, 0));
        assertEquals("NUMBER(4)", cross.getColumnTypeName(Types.SMALLINT, "year", 4, 0));
        assertEquals("TIMESTAMP(6)", cross.getColumnTypeName(Types.TIMESTAMP, "datetime(6)", 26, 6));
        assertEquals("VARCHAR2(20)", cross.getColumnTypeName(Types.TIME, "time", 10, 0));
        assertEquals("NUMBER(20)", cross.getColumnTypeName(Types.BIT, "bit(8)", 8, 0));
        assertEquals("RAW(16)", cross.getColumnTypeName(Types.BINARY, "binary(16)", 16, 0));
    }

    @Test
    void literalsAndValues() {
        OracleDialect dialect = new OracleDialect();
        assertEquals("HEXTORAW('0A')", dialect.getBinaryLiteral(new byte[]{10}));
        assertEquals("'10:20:30'", dialect.getTimeLiteral(LocalTime.of(10, 20, 30)));
        assertEquals("TIMESTAMP '2024-01-01 08:00:00 +08:00'", dialect.getTimestampWithTimeZoneLiteral(
                OffsetDateTime.of(2024, 1, 1, 8, 0, 0, 0, ZoneOffset.ofHours(8))));
        String longText = "中".repeat(2500);
        String literal = dialect.getStringLiteral(longText);
        assertTrue(literal.startsWith("TO_CLOB('") && literal.contains(") || TO_CLOB('"));
        assertEquals("1", dialect.getBooleanLiteral(true));
        assertEquals(1, dialect.getJdbcValue(true));
        assertEquals(0, dialect.getJdbcValue(false));
        assertEquals("10:20:30.5", dialect.getJdbcValue(LocalTime.of(10, 20, 30, 500_000_000)));
        assertEquals("x", dialect.getJdbcValue("x"));
    }

    @Test
    void partitions() {
        OracleDialect dialect = new OracleDialect();
        Map<String, Object> detail = new HashMap<>();
        detail.put("PARTITION_CLAUSE", "PARTITION BY RANGE (ID) (PARTITION P1 VALUES LESS THAN (10))");
        assertEquals("PARTITION BY RANGE (ID) (PARTITION P1 VALUES LESS THAN (10))",
                dialect.getDefinePartitionTableStatement(null, null, "T", "RANGE", "ID", detail));
        OracleDialect cross = new OracleDialect();
        cross.setSourceDbType(DbType.MYSQL);
        assertNull(cross.getDefinePartitionTableStatement(null, null, "T", "RANGE", "ID", detail));
        assertNull(dialect.getCreatePartitionTableStatement(null, null, "P", "T"));
    }
}
